name: homecare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Design System & UI
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Animations
  flutter_animate: ^4.5.0
  
  # HTTP Client
  http: ^1.1.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # Platform specific
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
